[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
tokio = "1.47.1"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "45cb5823f50ece7af86804d4331bd7ba2f6c5917"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "45cb5823f50ece7af86804d4331bd7ba2f6c5917"
package = "azalea-client"

[dependencies.common]
path = "../../common"