[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tokio = "1.47.1"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "fba8338becba614a3724f21447b85945e024cce3"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "fba8338becba614a3724f21447b85945e024cce3"
package = "azalea-client"

[dependencies.common]
path = "../../common"