[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
tokio = "1.47.1"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "12aeae07d2667cd188acf88190ed5c3f7983926a"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "12aeae07d2667cd188acf88190ed5c3f7983926a"
package = "azalea-client"

[dependencies.common]
path = "../../common"