[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tokio = "1.47.1"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "3aba53afad71369af95733143fff2fdc7f6a1fe8"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "3aba53afad71369af95733143fff2fdc7f6a1fe8"
package = "azalea-client"

[dependencies.common]
path = "../../common"