[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tokio = "1.47.1"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "8927a0fe65f5f89b4459956f19989f27f1e0981c"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "8927a0fe65f5f89b4459956f19989f27f1e0981c"
package = "azalea-client"

[dependencies.common]
path = "../../common"