[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tokio = "1.47.1"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "58c7b3fa01bb93833a46dbb7f611e8c86f871bf7"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "58c7b3fa01bb93833a46dbb7f611e8c86f871bf7"
package = "azalea-client"

[dependencies.common]
path = "../../common"