[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tokio = "1.47.1"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "7ae3eceee2a2a5577259b1aa066f97b1314e175d"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "7ae3eceee2a2a5577259b1aa066f97b1314e175d"
package = "azalea-client"

[dependencies.common]
path = "../../common"