[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tokio = "1.47.1"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "55a7db13ef028f5b6c6e87a81406b3525cea196f"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "55a7db13ef028f5b6c6e87a81406b3525cea196f"
package = "azalea-client"

[dependencies.common]
path = "../../common"