[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tokio = "1.47.1"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "aefa908e32032616cb356e7f4165cbb8922edbcf"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "aefa908e32032616cb356e7f4165cbb8922edbcf"
package = "azalea-client"

[dependencies.common]
path = "../../common"