[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
tokio = "1.47.1"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "827277555d44c606b16df91e1e724f3f0ab9e0a8"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "827277555d44c606b16df91e1e724f3f0ab9e0a8"
package = "azalea-client"

[dependencies.common]
path = "../../common"