[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokio = "1.47.1"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "643fcb98c0e6cdc63218dd39960d9053b209d9a6"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "643fcb98c0e6cdc63218dd39960d9053b209d9a6"
package = "azalea-client"

[dependencies.common]
path = "../../common"