[dependencies]
tokio = "1.45.1"
anyhow = "1.0.98"

[dependencies.azalea]
git = "https://github.com/azalea-rs/azalea"
rev = "ebc2e0c067d8b2c901ae02e032159e2c80eac7bc"

[dependencies.clap]
features = ["derive"]
version = "4.5"

[package]
edition = "2024"
version = "0.1.0"
name = "flex-update-mc-bot"

[package.metadata]
mc_version = "1.21.7"
