[dependencies]
anyhow = "1.0.69"
tokio = "1.26.0"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "118f649cf7a6e401ee2eccd385b04a5478fdd311"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "118f649cf7a6e401ee2eccd385b04a5478fdd311"
package = "azalea-client"

[package]
version = "0.1.0"
name = "flex-update-mc-bot"

[package.metadata]
mc_version = "1.19.3"
