[dependencies]
anyhow = "1.0.82"
tokio = "1.37.0"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "b55b8698186d6eb973aaa3c9e759c25aaba7e891"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "b55b8698186d6eb973aaa3c9e759c25aaba7e891"
package = "azalea-client"

[package]
edition = "2021"
version = "0.1.0"
name = "flex-update-mc-bot"

[package.metadata]
mc_version = "1.20.5"
