[dependencies]
anyhow = "1.0.98"
tokio = "1.45.1"

[dependencies.azalea]
git = "https://github.com/azalea-rs/azalea"
rev = "5564d475a285c5b40ac74d7123091ce6c63f8c17"

[dependencies.clap]
features = ["derive"]
version = "4.5"

[package]
edition = "2024"
name = "flex-update-mc-bot"
version = "0.1.0"

[package.metadata]
mc_version = "1.21.6"