name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]
        exclude:
          # Windows ARM64 not supported in GitHub Actions
          - os: windows-latest
            arch: arm64
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    
    - name: Add target for cross-compilation
      run: |
        case "${{ matrix.os }}" in
          "ubuntu-latest")
            if [ "${{ matrix.arch }}" = "arm64" ]; then
              rustup target add aarch64-unknown-linux-gnu
              sudo apt-get update
              sudo apt-get install -y gcc-aarch64-linux-gnu
            fi
            ;;
          "macos-latest")
            if [ "${{ matrix.arch }}" = "arm64" ]; then
              rustup target add aarch64-apple-darwin
            fi
            ;;
        esac
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
    
    - name: Get Minecraft version
      id: mc-version
      run: |
        # Extract MC version from bot/Cargo.toml metadata
        cd bot
        MC_VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].metadata.mc_version // "unknown"')
        echo "mc_version=${MC_VERSION}" >> $GITHUB_OUTPUT
    
    - name: Build
      run: |
        # Determine target based on matrix
        case "${{ matrix.os }}" in
          "ubuntu-latest")
            if [ "${{ matrix.arch }}" = "arm64" ]; then
              TARGET="aarch64-unknown-linux-gnu"
            else
              TARGET="x86_64-unknown-linux-gnu"
            fi
            ;;
          "windows-latest")
            TARGET="x86_64-pc-windows-msvc"
            ;;
          "macos-latest")
            if [ "${{ matrix.arch }}" = "arm64" ]; then
              TARGET="aarch64-apple-darwin"
            else
              TARGET="x86_64-apple-darwin"
            fi
            ;;
        esac
        
        # Use the Rust build tool
        cargo run --bin build-bot -p tools -- --target ${TARGET} --output-dir artifacts
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flex-update-mc-bot-${{ steps.mc-version.outputs.mc_version }}-${{ matrix.os }}-${{ matrix.arch }}
        path: artifacts/
        retention-days: 7